version: '3.8'
services:
  smb:
    container_name: smb
    image: smb:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SMB_USER: user
        SMB_PASSWORD: pass
    volumes:
      - /mnt/storage1:/mnt/storage1:rw
      - /mnt/storage2:/mnt/storage2:rw
    tty: yes
    restart: always
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    networks:
      - default

networks:
  default: